services:
  scrapyd:
    build:
      context: .
      dockerfile: ./webnews_parser/Dockerfile
      ssh:
        - default
    container_name: scrapyd-ff-server
    ports:
      - "6800:6800"
    volumes:
      - ./webnews_parser/scrapyd.conf:/etc/scrapyd/scrapyd.conf
    env_file:
      - .env
    restart: unless-stopped
    networks:
        - app_network
        - flux-backend_app_network
 

networks:
  app_network:
    driver: bridge
  flux-backend_app_network:  # Define the external network
    external: true