services:
  scrapyd:
    build:
      context: .
      dockerfile: ./src/Dockerfile
      ssh:
        - default
    container_name: scrapyd-ff-server
    ports:
      - "6800:6800"
    volumes:
      - ./src/scrapyd.conf:/etc/scrapyd/scrapyd.conf
    env_file:
      - .env
    restart: unless-stopped
    networks:
        - app_network
 

networks:
  app_network:
    driver: bridge